json.extract! fundraising_campaign,
  :id,
  :name,
  :url,
  :target_amount,
  :total_raised_amount,
  :donor_count,
  :location,
  :about_campaign,
  :main_image,
  :youtube_url,
  :start_datetime,
  :end_datetime,
  :published,
  :organization_id,
  :created_at,
  :updated_at
