AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/**/*"
    - "docker/**/*"
    - "log/**/*"
    - "public/**/*"
    - "storage/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "config.ru"
    - "Rakefile"
    - "**/*.jbuilder"

Bundler/OrderedGems:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - "app/services/**/*"

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: false
