AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/**/*"
    - "docker/**/*"
    - "log/**/*"
    - "public/**/*"
    - "storage/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "config.ru"
    - "Rakefile"
    - "**/*.jbuilder"

Bundler/OrderedGems:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
