json.extract! organization,
  :id,
  :name,
  :location,
  :email,
  :contact_no,
  :website_url,
  :facebook_url,
  :youtube_url,
  :person_in_charge_name,
  :avatar_url,
  :video_url,
  :image_url,
  :charity
