json.extract! volunteer_event,
  :id,
  :name,
  :url,
  :openings,
  :volunteer_count,
  :location,
  :about_event,
  :main_image,
  :youtube_url,
  :start_datetime,
  :end_datetime,
  :sign_up_deadline,
  :published,
  :organization_id,
  :created_at,
  :updated_at
