json.extract! charitable_aid,
  :id,
  :name,
  :url,
  :openings,
  :receiver_count,
  :location,
  :about_aid,
  :main_image,
  :youtube_url,
  :application_deadline,
  :published,
  :organization_id,
  :created_at,
  :updated_at
